services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: lukas
      POSTGRES_PASSWORD: 741852
      POSTGRES_DB: sensor_database
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./INSTALL:/docker-entrypoint-INITDB.d/